// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_logs (
    restaurant_id, entity, status, records_processed,
    records_inserted, records_updated, records_skipped, records_failed,
    cursor_from, cursor_to, triggered_by, details
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, started_at
`

type CreateSyncLogParams struct {
	RestaurantID     uuid.UUID             `json:"restaurant_id"`
	Entity           SyncEntity            `json:"entity"`
	Status           string                `json:"status"`
	RecordsProcessed int32                 `json:"records_processed"`
	RecordsInserted  int32                 `json:"records_inserted"`
	RecordsUpdated   int32                 `json:"records_updated"`
	RecordsSkipped   int32                 `json:"records_skipped"`
	RecordsFailed    int32                 `json:"records_failed"`
	CursorFrom       sql.NullTime          `json:"cursor_from"`
	CursorTo         sql.NullTime          `json:"cursor_to"`
	TriggeredBy      string                `json:"triggered_by"`
	Details          pqtype.NullRawMessage `json:"details"`
}

type CreateSyncLogRow struct {
	ID        uuid.UUID `json:"id"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (CreateSyncLogRow, error) {
	row := q.db.QueryRowContext(ctx, createSyncLog,
		arg.RestaurantID,
		arg.Entity,
		arg.Status,
		arg.RecordsProcessed,
		arg.RecordsInserted,
		arg.RecordsUpdated,
		arg.RecordsSkipped,
		arg.RecordsFailed,
		arg.CursorFrom,
		arg.CursorTo,
		arg.TriggeredBy,
		arg.Details,
	)
	var i CreateSyncLogRow
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}

const getLatestSyncByEntity = `-- name: GetLatestSyncByEntity :many
SELECT DISTINCT ON (entity) id, restaurant_id, entity, status, records_processed, records_inserted, records_updated, records_skipped, records_failed, cursor_from, cursor_to, started_at, finished_at, triggered_by, details
FROM sync_logs
WHERE restaurant_id = $1
ORDER BY entity, started_at DESC
`

func (q *Queries) GetLatestSyncByEntity(ctx context.Context, restaurantID uuid.UUID) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, getLatestSyncByEntity, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncLog
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Entity,
			&i.Status,
			&i.RecordsProcessed,
			&i.RecordsInserted,
			&i.RecordsUpdated,
			&i.RecordsSkipped,
			&i.RecordsFailed,
			&i.CursorFrom,
			&i.CursorTo,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TriggeredBy,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncErrorsUnresolved = `-- name: ListSyncErrorsUnresolved :many
SELECT id, restaurant_id, sync_log_id, entity, clover_id, error_code, error_message, http_status, retry_after, is_resolved, resolved_at, retry_count, created_at
FROM sync_errors
WHERE restaurant_id = $1 AND is_resolved = false
ORDER BY created_at DESC
LIMIT $2
`

type ListSyncErrorsUnresolvedParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) ListSyncErrorsUnresolved(ctx context.Context, arg ListSyncErrorsUnresolvedParams) ([]SyncError, error) {
	rows, err := q.db.QueryContext(ctx, listSyncErrorsUnresolved, arg.RestaurantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncError
	for rows.Next() {
		var i SyncError
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.SyncLogID,
			&i.Entity,
			&i.CloverID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.HttpStatus,
			&i.RetryAfter,
			&i.IsResolved,
			&i.ResolvedAt,
			&i.RetryCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncLogs = `-- name: ListSyncLogs :many
SELECT id, restaurant_id, entity, status, records_processed, records_inserted, records_updated, records_skipped, records_failed, cursor_from, cursor_to, started_at, finished_at, triggered_by, details
FROM sync_logs
WHERE restaurant_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListSyncLogsParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) ListSyncLogs(ctx context.Context, arg ListSyncLogsParams) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, listSyncLogs, arg.RestaurantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncLog
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Entity,
			&i.Status,
			&i.RecordsProcessed,
			&i.RecordsInserted,
			&i.RecordsUpdated,
			&i.RecordsSkipped,
			&i.RecordsFailed,
			&i.CursorFrom,
			&i.CursorTo,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TriggeredBy,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
