// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createMerchant = `-- name: CreateMerchant :exec
INSERT INTO restaurants (
    id, name, clover_merchant_id,
    access_token, refresh_token,
    access_token_expires_at, refresh_token_expires_at,
    clover_env, is_connected, is_active,
    ticket_completo_rules, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateMerchantParams struct {
	ID                    uuid.UUID             `json:"id"`
	Name                  sql.NullString        `json:"name"`
	CloverMerchantID      sql.NullString        `json:"clover_merchant_id"`
	AccessToken           []byte                `json:"access_token"`
	RefreshToken          []byte                `json:"refresh_token"`
	AccessTokenExpiresAt  sql.NullTime          `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime          `json:"refresh_token_expires_at"`
	CloverEnv             string                `json:"clover_env"`
	IsConnected           bool                  `json:"is_connected"`
	IsActive              bool                  `json:"is_active"`
	TicketCompletoRules   pqtype.NullRawMessage `json:"ticket_completo_rules"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) error {
	_, err := q.db.ExecContext(ctx, createMerchant,
		arg.ID,
		arg.Name,
		arg.CloverMerchantID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.CloverEnv,
		arg.IsConnected,
		arg.IsActive,
		arg.TicketCompletoRules,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMerchant = `-- name: DeleteMerchant :exec
UPDATE restaurants SET is_active = false, updated_at = $2 WHERE id = $1
`

type DeleteMerchantParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) DeleteMerchant(ctx context.Context, arg DeleteMerchantParams) error {
	_, err := q.db.ExecContext(ctx, deleteMerchant, arg.ID, arg.UpdatedAt)
	return err
}

const getMerchantByCloverMerchantID = `-- name: GetMerchantByCloverMerchantID :one
SELECT id, name, clover_merchant_id,
    access_token, refresh_token,
    access_token_expires_at, refresh_token_expires_at,
    clover_env, is_connected, is_active,
    ticket_completo_rules, created_at, updated_at
FROM restaurants
WHERE clover_merchant_id = $1
`

func (q *Queries) GetMerchantByCloverMerchantID(ctx context.Context, cloverMerchantID sql.NullString) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByCloverMerchantID, cloverMerchantID)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CloverMerchantID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CloverEnv,
		&i.IsConnected,
		&i.IsActive,
		&i.TicketCompletoRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, name, clover_merchant_id,
    access_token, refresh_token,
    access_token_expires_at, refresh_token_expires_at,
    clover_env, is_connected, is_active,
    ticket_completo_rules, created_at, updated_at
FROM restaurants
WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id uuid.UUID) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CloverMerchantID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CloverEnv,
		&i.IsConnected,
		&i.IsActive,
		&i.TicketCompletoRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, name, clover_merchant_id,
    access_token, refresh_token,
    access_token_expires_at, refresh_token_expires_at,
    clover_env, is_connected, is_active,
    ticket_completo_rules, created_at, updated_at
FROM restaurants
WHERE is_active = true
`

func (q *Queries) ListMerchants(ctx context.Context) ([]Restaurant, error) {
	rows, err := q.db.QueryContext(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Restaurant
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CloverMerchantID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.CloverEnv,
			&i.IsConnected,
			&i.IsActive,
			&i.TicketCompletoRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchant = `-- name: UpdateMerchant :exec
UPDATE restaurants SET
    name = $2,
    clover_merchant_id = $3,
    clover_env = $4,
    is_connected = $5,
    is_active = $6,
    ticket_completo_rules = $7,
    updated_at = $8
WHERE id = $1
`

type UpdateMerchantParams struct {
	ID                  uuid.UUID             `json:"id"`
	Name                sql.NullString        `json:"name"`
	CloverMerchantID    sql.NullString        `json:"clover_merchant_id"`
	CloverEnv           string                `json:"clover_env"`
	IsConnected         bool                  `json:"is_connected"`
	IsActive            bool                  `json:"is_active"`
	TicketCompletoRules pqtype.NullRawMessage `json:"ticket_completo_rules"`
	UpdatedAt           time.Time             `json:"updated_at"`
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchant,
		arg.ID,
		arg.Name,
		arg.CloverMerchantID,
		arg.CloverEnv,
		arg.IsConnected,
		arg.IsActive,
		arg.TicketCompletoRules,
		arg.UpdatedAt,
	)
	return err
}

const updateMerchantTokens = `-- name: UpdateMerchantTokens :exec
UPDATE restaurants SET
    access_token = $2,
    refresh_token = $3,
    access_token_expires_at = $4,
    refresh_token_expires_at = $5,
    updated_at = $6
WHERE id = $1
`

type UpdateMerchantTokensParams struct {
	ID                    uuid.UUID    `json:"id"`
	AccessToken           []byte       `json:"access_token"`
	RefreshToken          []byte       `json:"refresh_token"`
	AccessTokenExpiresAt  sql.NullTime `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime `json:"refresh_token_expires_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

func (q *Queries) UpdateMerchantTokens(ctx context.Context, arg UpdateMerchantTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.UpdatedAt,
	)
	return err
}
