// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deactivateEmployee = `-- name: DeactivateEmployee :exec
UPDATE employees
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateEmployee, id)
	return err
}

const getEmployeeByCloverID = `-- name: GetEmployeeByCloverID :one
SELECT id, restaurant_id, clover_employee_id, name, email, phone, role, is_active, created_at, updated_at, synced_at FROM employees
WHERE restaurant_id = $1 AND clover_employee_id = $2
LIMIT 1
`

type GetEmployeeByCloverIDParams struct {
	RestaurantID     uuid.UUID `json:"restaurant_id"`
	CloverEmployeeID string    `json:"clover_employee_id"`
}

func (q *Queries) GetEmployeeByCloverID(ctx context.Context, arg GetEmployeeByCloverIDParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByCloverID, arg.RestaurantID, arg.CloverEmployeeID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverEmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, restaurant_id, clover_employee_id, name, email, phone, role, is_active, created_at, updated_at, synced_at FROM employees
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id uuid.UUID) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverEmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const listEmployeesByRestaurant = `-- name: ListEmployeesByRestaurant :many
SELECT id, restaurant_id, clover_employee_id, name, email, phone, role, is_active, created_at, updated_at, synced_at FROM employees
WHERE restaurant_id = $1
ORDER BY name
`

func (q *Queries) ListEmployeesByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CloverEmployeeID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmployee = `-- name: UpsertEmployee :one
INSERT INTO employees (
    id,
    restaurant_id,
    clover_employee_id,
    name,
    email,
    phone,
    role,
    is_active,
    created_at,
    updated_at,
    synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (restaurant_id, clover_employee_id)
DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    role = EXCLUDED.role,
    is_active = EXCLUDED.is_active,
    updated_at = EXCLUDED.updated_at,
    synced_at = EXCLUDED.synced_at
RETURNING id, restaurant_id, clover_employee_id, name, email, phone, role, is_active, created_at, updated_at, synced_at
`

type UpsertEmployeeParams struct {
	ID               uuid.UUID      `json:"id"`
	RestaurantID     uuid.UUID      `json:"restaurant_id"`
	CloverEmployeeID string         `json:"clover_employee_id"`
	Name             string         `json:"name"`
	Email            sql.NullString `json:"email"`
	Phone            sql.NullString `json:"phone"`
	Role             sql.NullString `json:"role"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	SyncedAt         time.Time      `json:"synced_at"`
}

func (q *Queries) UpsertEmployee(ctx context.Context, arg UpsertEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, upsertEmployee,
		arg.ID,
		arg.RestaurantID,
		arg.CloverEmployeeID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncedAt,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverEmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}
