// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveAnalyticCategories = `-- name: CountActiveAnalyticCategories :one
SELECT COUNT(*)::int AS total_categories
FROM analytic_categories
WHERE restaurant_id = $1 AND is_active = true
`

func (q *Queries) CountActiveAnalyticCategories(ctx context.Context, restaurantID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countActiveAnalyticCategories, restaurantID)
	var total_categories int32
	err := row.Scan(&total_categories)
	return total_categories, err
}

const getCategoryCoverage = `-- name: GetCategoryCoverage :many
SELECT
    e.id AS employee_id,
    e.name AS employee_name,
    COUNT(DISTINCT ocs.analytic_category_id)::int AS categories_covered
FROM employees e
JOIN orders o ON e.id = o.employee_id
JOIN order_category_summary ocs ON o.id = ocs.order_id
WHERE e.restaurant_id = $1
  AND o.created_time >= $2
  AND o.created_time < $3
GROUP BY e.id, e.name
ORDER BY categories_covered DESC
`

type GetCategoryCoverageParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
}

type GetCategoryCoverageRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeName      string    `json:"employee_name"`
	CategoriesCovered int32     `json:"categories_covered"`
}

func (q *Queries) GetCategoryCoverage(ctx context.Context, arg GetCategoryCoverageParams) ([]GetCategoryCoverageRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryCoverage, arg.RestaurantID, arg.CreatedTime, arg.CreatedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryCoverageRow
	for rows.Next() {
		var i GetCategoryCoverageRow
		if err := rows.Scan(&i.EmployeeID, &i.EmployeeName, &i.CategoriesCovered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderCategoryBreakdown = `-- name: GetOrderCategoryBreakdown :many
SELECT
    ocs.order_id,
    ac.slug AS category_slug,
    ocs.total_quantity
FROM order_category_summary ocs
JOIN analytic_categories ac ON ocs.analytic_category_id = ac.id
JOIN orders o ON ocs.order_id = o.id
WHERE ocs.restaurant_id = $1
  AND o.created_time >= $2
  AND o.created_time < $3
  AND ac.is_active = true
ORDER BY ocs.order_id
`

type GetOrderCategoryBreakdownParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
}

type GetOrderCategoryBreakdownRow struct {
	OrderID       uuid.UUID `json:"order_id"`
	CategorySlug  string    `json:"category_slug"`
	TotalQuantity int32     `json:"total_quantity"`
}

func (q *Queries) GetOrderCategoryBreakdown(ctx context.Context, arg GetOrderCategoryBreakdownParams) ([]GetOrderCategoryBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderCategoryBreakdown, arg.RestaurantID, arg.CreatedTime, arg.CreatedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderCategoryBreakdownRow
	for rows.Next() {
		var i GetOrderCategoryBreakdownRow
		if err := rows.Scan(&i.OrderID, &i.CategorySlug, &i.TotalQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesByEmployee = `-- name: GetSalesByEmployee :many
SELECT
    e.id AS employee_id,
    e.name AS employee_name,
    COUNT(o.id)::int AS order_count,
    COALESCE(SUM(o.total_amount), 0)::bigint AS total_sales,
    COALESCE(AVG(o.total_amount), 0)::float8 AS avg_ticket
FROM employees e
LEFT JOIN orders o ON e.id = o.employee_id AND o.created_time >= $2 AND o.created_time < $3
WHERE e.restaurant_id = $1 AND e.is_active = true
GROUP BY e.id, e.name
ORDER BY total_sales DESC
`

type GetSalesByEmployeeParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
}

type GetSalesByEmployeeRow struct {
	EmployeeID   uuid.UUID `json:"employee_id"`
	EmployeeName string    `json:"employee_name"`
	OrderCount   int32     `json:"order_count"`
	TotalSales   int64     `json:"total_sales"`
	AvgTicket    float64   `json:"avg_ticket"`
}

func (q *Queries) GetSalesByEmployee(ctx context.Context, arg GetSalesByEmployeeParams) ([]GetSalesByEmployeeRow, error) {
	rows, err := q.db.QueryContext(ctx, getSalesByEmployee, arg.RestaurantID, arg.CreatedTime, arg.CreatedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSalesByEmployeeRow
	for rows.Next() {
		var i GetSalesByEmployeeRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeName,
			&i.OrderCount,
			&i.TotalSales,
			&i.AvgTicket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesSummary = `-- name: GetSalesSummary :one
SELECT
    COUNT(*)::int AS order_count,
    COALESCE(SUM(total_amount), 0)::bigint AS total_sales,
    COALESCE(AVG(total_amount), 0)::float8 AS avg_ticket,
    COALESCE(SUM(tax_amount), 0)::bigint AS total_tax,
    COALESCE(SUM(tip_amount), 0)::bigint AS total_tips,
    COALESCE(SUM(discount_amount), 0)::bigint AS total_discounts
FROM orders
WHERE restaurant_id = $1
  AND created_time >= $2
  AND created_time < $3
`

type GetSalesSummaryParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
}

type GetSalesSummaryRow struct {
	OrderCount     int32   `json:"order_count"`
	TotalSales     int64   `json:"total_sales"`
	AvgTicket      float64 `json:"avg_ticket"`
	TotalTax       int64   `json:"total_tax"`
	TotalTips      int64   `json:"total_tips"`
	TotalDiscounts int64   `json:"total_discounts"`
}

func (q *Queries) GetSalesSummary(ctx context.Context, arg GetSalesSummaryParams) (GetSalesSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesSummary, arg.RestaurantID, arg.CreatedTime, arg.CreatedTime_2)
	var i GetSalesSummaryRow
	err := row.Scan(
		&i.OrderCount,
		&i.TotalSales,
		&i.AvgTicket,
		&i.TotalTax,
		&i.TotalTips,
		&i.TotalDiscounts,
	)
	return i, err
}

const getTopProducts = `-- name: GetTopProducts :many
SELECT
    p.id AS product_id,
    p.name AS product_name,
    SUM(oi.quantity)::bigint AS total_quantity,
    SUM(oi.total_price)::bigint AS total_revenue
FROM order_items oi
JOIN orders o ON oi.order_id = o.id
JOIN products p ON oi.product_id = p.id
WHERE o.restaurant_id = $1
  AND o.created_time >= $2
  AND o.created_time < $3
  AND p.is_deleted = false
GROUP BY p.id, p.name
ORDER BY total_quantity DESC
LIMIT $4
`

type GetTopProductsParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
	Limit         int32     `json:"limit"`
}

type GetTopProductsRow struct {
	ProductID     uuid.UUID `json:"product_id"`
	ProductName   string    `json:"product_name"`
	TotalQuantity int64     `json:"total_quantity"`
	TotalRevenue  int64     `json:"total_revenue"`
}

func (q *Queries) GetTopProducts(ctx context.Context, arg GetTopProductsParams) ([]GetTopProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopProducts,
		arg.RestaurantID,
		arg.CreatedTime,
		arg.CreatedTime_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopProductsRow
	for rows.Next() {
		var i GetTopProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.TotalQuantity,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
