// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getPaymentByCloverID = `-- name: GetPaymentByCloverID :one
SELECT id, restaurant_id, clover_payment_id, order_id, employee_id, amount, tip_amount, tax_amount, payment_type, card_type, result, external_payment_id, created_time, modified_time, synced_at FROM payments
WHERE restaurant_id = $1 AND clover_payment_id = $2
LIMIT 1
`

type GetPaymentByCloverIDParams struct {
	RestaurantID    uuid.UUID `json:"restaurant_id"`
	CloverPaymentID string    `json:"clover_payment_id"`
}

func (q *Queries) GetPaymentByCloverID(ctx context.Context, arg GetPaymentByCloverIDParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByCloverID, arg.RestaurantID, arg.CloverPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverPaymentID,
		&i.OrderID,
		&i.EmployeeID,
		&i.Amount,
		&i.TipAmount,
		&i.TaxAmount,
		&i.PaymentType,
		&i.CardType,
		&i.Result,
		&i.ExternalPaymentID,
		&i.CreatedTime,
		&i.ModifiedTime,
		&i.SyncedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, restaurant_id, clover_payment_id, order_id, employee_id, amount, tip_amount, tax_amount, payment_type, card_type, result, external_payment_id, created_time, modified_time, synced_at FROM payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverPaymentID,
		&i.OrderID,
		&i.EmployeeID,
		&i.Amount,
		&i.TipAmount,
		&i.TaxAmount,
		&i.PaymentType,
		&i.CardType,
		&i.Result,
		&i.ExternalPaymentID,
		&i.CreatedTime,
		&i.ModifiedTime,
		&i.SyncedAt,
	)
	return i, err
}

const listPaymentsByRestaurantAndDate = `-- name: ListPaymentsByRestaurantAndDate :many
SELECT id, restaurant_id, clover_payment_id, order_id, employee_id, amount, tip_amount, tax_amount, payment_type, card_type, result, external_payment_id, created_time, modified_time, synced_at FROM payments
WHERE restaurant_id = $1
  AND created_time >= $2
  AND created_time < $3
ORDER BY created_time DESC
`

type ListPaymentsByRestaurantAndDateParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
}

func (q *Queries) ListPaymentsByRestaurantAndDate(ctx context.Context, arg ListPaymentsByRestaurantAndDateParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByRestaurantAndDate, arg.RestaurantID, arg.CreatedTime, arg.CreatedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CloverPaymentID,
			&i.OrderID,
			&i.EmployeeID,
			&i.Amount,
			&i.TipAmount,
			&i.TaxAmount,
			&i.PaymentType,
			&i.CardType,
			&i.Result,
			&i.ExternalPaymentID,
			&i.CreatedTime,
			&i.ModifiedTime,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPayment = `-- name: UpsertPayment :one
INSERT INTO payments (
    id, restaurant_id, clover_payment_id, order_id, employee_id,
    amount, tip_amount, tax_amount, payment_type, card_type, result,
    external_payment_id, created_time, modified_time, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (restaurant_id, clover_payment_id)
DO UPDATE SET
    order_id = EXCLUDED.order_id,
    employee_id = EXCLUDED.employee_id,
    amount = EXCLUDED.amount,
    tip_amount = EXCLUDED.tip_amount,
    tax_amount = EXCLUDED.tax_amount,
    payment_type = EXCLUDED.payment_type,
    card_type = EXCLUDED.card_type,
    result = EXCLUDED.result,
    external_payment_id = EXCLUDED.external_payment_id,
    created_time = EXCLUDED.created_time,
    modified_time = EXCLUDED.modified_time,
    synced_at = EXCLUDED.synced_at
RETURNING id, restaurant_id, clover_payment_id, order_id, employee_id, amount, tip_amount, tax_amount, payment_type, card_type, result, external_payment_id, created_time, modified_time, synced_at
`

type UpsertPaymentParams struct {
	ID                uuid.UUID      `json:"id"`
	RestaurantID      uuid.UUID      `json:"restaurant_id"`
	CloverPaymentID   string         `json:"clover_payment_id"`
	OrderID           uuid.NullUUID  `json:"order_id"`
	EmployeeID        uuid.NullUUID  `json:"employee_id"`
	Amount            int64          `json:"amount"`
	TipAmount         int64          `json:"tip_amount"`
	TaxAmount         int64          `json:"tax_amount"`
	PaymentType       sql.NullString `json:"payment_type"`
	CardType          sql.NullString `json:"card_type"`
	Result            string         `json:"result"`
	ExternalPaymentID sql.NullString `json:"external_payment_id"`
	CreatedTime       time.Time      `json:"created_time"`
	ModifiedTime      time.Time      `json:"modified_time"`
	SyncedAt          time.Time      `json:"synced_at"`
}

func (q *Queries) UpsertPayment(ctx context.Context, arg UpsertPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, upsertPayment,
		arg.ID,
		arg.RestaurantID,
		arg.CloverPaymentID,
		arg.OrderID,
		arg.EmployeeID,
		arg.Amount,
		arg.TipAmount,
		arg.TaxAmount,
		arg.PaymentType,
		arg.CardType,
		arg.Result,
		arg.ExternalPaymentID,
		arg.CreatedTime,
		arg.ModifiedTime,
		arg.SyncedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverPaymentID,
		&i.OrderID,
		&i.EmployeeID,
		&i.Amount,
		&i.TipAmount,
		&i.TaxAmount,
		&i.PaymentType,
		&i.CardType,
		&i.Result,
		&i.ExternalPaymentID,
		&i.CreatedTime,
		&i.ModifiedTime,
		&i.SyncedAt,
	)
	return i, err
}
