// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type SyncEntity string

const (
	SyncEntityOrders    SyncEntity = "orders"
	SyncEntityItems     SyncEntity = "items"
	SyncEntityEmployees SyncEntity = "employees"
	SyncEntityPayments  SyncEntity = "payments"
	SyncEntityExport    SyncEntity = "export"
)

func (e *SyncEntity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncEntity(s)
	case string:
		*e = SyncEntity(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncEntity: %T", src)
	}
	return nil
}

type NullSyncEntity struct {
	SyncEntity SyncEntity `json:"sync_entity"`
	Valid      bool       `json:"valid"` // Valid is true if SyncEntity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncEntity) Scan(value interface{}) error {
	if value == nil {
		ns.SyncEntity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncEntity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncEntity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncEntity), nil
}

type AnalyticCategory struct {
	ID           uuid.UUID      `json:"id"`
	RestaurantID uuid.UUID      `json:"restaurant_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	DisplayOrder int32          `json:"display_order"`
	Color        sql.NullString `json:"color"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Category struct {
	ID               uuid.UUID     `json:"id"`
	RestaurantID     uuid.UUID     `json:"restaurant_id"`
	CloverCategoryID string        `json:"clover_category_id"`
	Name             string        `json:"name"`
	SortOrder        sql.NullInt32 `json:"sort_order"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	SyncedAt         time.Time     `json:"synced_at"`
}

type CategoryMapping struct {
	ID                 uuid.UUID      `json:"id"`
	RestaurantID       uuid.UUID      `json:"restaurant_id"`
	CategoryID         uuid.UUID      `json:"category_id"`
	AnalyticCategoryID uuid.UUID      `json:"analytic_category_id"`
	MappedBy           sql.NullString `json:"mapped_by"`
	MappedAt           time.Time      `json:"mapped_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Employee struct {
	ID               uuid.UUID      `json:"id"`
	RestaurantID     uuid.UUID      `json:"restaurant_id"`
	CloverEmployeeID string         `json:"clover_employee_id"`
	Name             string         `json:"name"`
	Email            sql.NullString `json:"email"`
	Phone            sql.NullString `json:"phone"`
	Role             sql.NullString `json:"role"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	SyncedAt         time.Time      `json:"synced_at"`
}

type Order struct {
	ID                  uuid.UUID      `json:"id"`
	RestaurantID        uuid.UUID      `json:"restaurant_id"`
	CloverOrderID       string         `json:"clover_order_id"`
	EmployeeID          uuid.NullUUID  `json:"employee_id"`
	OrderNumber         sql.NullString `json:"order_number"`
	OrderType           sql.NullString `json:"order_type"`
	State               string         `json:"state"`
	TotalAmount         int64          `json:"total_amount"`
	TaxAmount           int64          `json:"tax_amount"`
	DiscountAmount      int64          `json:"discount_amount"`
	TipAmount           int64          `json:"tip_amount"`
	CreatedTime         time.Time      `json:"created_time"`
	ModifiedTime        time.Time      `json:"modified_time"`
	PayType             sql.NullString `json:"pay_type"`
	ItemCount           int32          `json:"item_count"`
	UniqueCategoryCount int32          `json:"unique_category_count"`
	TotalQuantity       int32          `json:"total_quantity"`
	SyncedAt            time.Time      `json:"synced_at"`
}

type OrderCategorySummary struct {
	ID                 uuid.UUID `json:"id"`
	RestaurantID       uuid.UUID `json:"restaurant_id"`
	OrderID            uuid.UUID `json:"order_id"`
	AnalyticCategoryID uuid.UUID `json:"analytic_category_id"`
	ItemCount          int32     `json:"item_count"`
	TotalQuantity      int32     `json:"total_quantity"`
	TotalAmount        int64     `json:"total_amount"`
}

type OrderItem struct {
	ID                 uuid.UUID      `json:"id"`
	RestaurantID       uuid.UUID      `json:"restaurant_id"`
	OrderID            uuid.UUID      `json:"order_id"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	CloverLineItemID   sql.NullString `json:"clover_line_item_id"`
	Name               string         `json:"name"`
	Quantity           int32          `json:"quantity"`
	UnitPrice          int64          `json:"unit_price"`
	TotalPrice         int64          `json:"total_price"`
	AnalyticCategoryID uuid.NullUUID  `json:"analytic_category_id"`
	CreatedAt          time.Time      `json:"created_at"`
	SyncedAt           time.Time      `json:"synced_at"`
}

type Payment struct {
	ID                uuid.UUID      `json:"id"`
	RestaurantID      uuid.UUID      `json:"restaurant_id"`
	CloverPaymentID   string         `json:"clover_payment_id"`
	OrderID           uuid.NullUUID  `json:"order_id"`
	EmployeeID        uuid.NullUUID  `json:"employee_id"`
	Amount            int64          `json:"amount"`
	TipAmount         int64          `json:"tip_amount"`
	TaxAmount         int64          `json:"tax_amount"`
	PaymentType       sql.NullString `json:"payment_type"`
	CardType          sql.NullString `json:"card_type"`
	Result            string         `json:"result"`
	ExternalPaymentID sql.NullString `json:"external_payment_id"`
	CreatedTime       time.Time      `json:"created_time"`
	ModifiedTime      time.Time      `json:"modified_time"`
	SyncedAt          time.Time      `json:"synced_at"`
}

type Product struct {
	ID           uuid.UUID      `json:"id"`
	RestaurantID uuid.UUID      `json:"restaurant_id"`
	CloverItemID string         `json:"clover_item_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        int64          `json:"price"`
	Cost         sql.NullInt64  `json:"cost"`
	Sku          sql.NullString `json:"sku"`
	CategoryID   uuid.NullUUID  `json:"category_id"`
	IsAvailable  bool           `json:"is_available"`
	IsDeleted    bool           `json:"is_deleted"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SyncedAt     time.Time      `json:"synced_at"`
}

type Restaurant struct {
	ID                    uuid.UUID             `json:"id"`
	Name                  sql.NullString        `json:"name"`
	CloverMerchantID      sql.NullString        `json:"clover_merchant_id"`
	AccessToken           []byte                `json:"access_token"`
	RefreshToken          []byte                `json:"refresh_token"`
	AccessTokenExpiresAt  sql.NullTime          `json:"access_token_expires_at"`
	RefreshTokenExpiresAt sql.NullTime          `json:"refresh_token_expires_at"`
	CloverEnv             string                `json:"clover_env"`
	IsConnected           bool                  `json:"is_connected"`
	IsActive              bool                  `json:"is_active"`
	TicketCompletoRules   pqtype.NullRawMessage `json:"ticket_completo_rules"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
}

type SyncError struct {
	ID           uuid.UUID      `json:"id"`
	RestaurantID uuid.UUID      `json:"restaurant_id"`
	SyncLogID    uuid.NullUUID  `json:"sync_log_id"`
	Entity       SyncEntity     `json:"entity"`
	CloverID     sql.NullString `json:"clover_id"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage string         `json:"error_message"`
	HttpStatus   sql.NullInt32  `json:"http_status"`
	RetryAfter   sql.NullInt32  `json:"retry_after"`
	IsResolved   bool           `json:"is_resolved"`
	ResolvedAt   sql.NullTime   `json:"resolved_at"`
	RetryCount   int32          `json:"retry_count"`
	CreatedAt    time.Time      `json:"created_at"`
}

type SyncLog struct {
	ID               uuid.UUID             `json:"id"`
	RestaurantID     uuid.UUID             `json:"restaurant_id"`
	Entity           SyncEntity            `json:"entity"`
	Status           string                `json:"status"`
	RecordsProcessed int32                 `json:"records_processed"`
	RecordsInserted  int32                 `json:"records_inserted"`
	RecordsUpdated   int32                 `json:"records_updated"`
	RecordsSkipped   int32                 `json:"records_skipped"`
	RecordsFailed    int32                 `json:"records_failed"`
	CursorFrom       sql.NullTime          `json:"cursor_from"`
	CursorTo         sql.NullTime          `json:"cursor_to"`
	StartedAt        time.Time             `json:"started_at"`
	FinishedAt       sql.NullTime          `json:"finished_at"`
	TriggeredBy      string                `json:"triggered_by"`
	Details          pqtype.NullRawMessage `json:"details"`
}
