// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteOrderByCloverID = `-- name: DeleteOrderByCloverID :exec
DELETE FROM orders
WHERE restaurant_id = $1 AND clover_order_id = $2
`

type DeleteOrderByCloverIDParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CloverOrderID string    `json:"clover_order_id"`
}

func (q *Queries) DeleteOrderByCloverID(ctx context.Context, arg DeleteOrderByCloverIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrderByCloverID, arg.RestaurantID, arg.CloverOrderID)
	return err
}

const getOrderByCloverOrderID = `-- name: GetOrderByCloverOrderID :one
SELECT id, restaurant_id, clover_order_id, employee_id, order_number, order_type, state, total_amount, tax_amount, discount_amount, tip_amount, created_time, modified_time, pay_type, item_count, unique_category_count, total_quantity, synced_at FROM orders
WHERE restaurant_id = $1 AND clover_order_id = $2
LIMIT 1
`

type GetOrderByCloverOrderIDParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CloverOrderID string    `json:"clover_order_id"`
}

func (q *Queries) GetOrderByCloverOrderID(ctx context.Context, arg GetOrderByCloverOrderIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByCloverOrderID, arg.RestaurantID, arg.CloverOrderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverOrderID,
		&i.EmployeeID,
		&i.OrderNumber,
		&i.OrderType,
		&i.State,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.TipAmount,
		&i.CreatedTime,
		&i.ModifiedTime,
		&i.PayType,
		&i.ItemCount,
		&i.UniqueCategoryCount,
		&i.TotalQuantity,
		&i.SyncedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one

SELECT id, restaurant_id, clover_order_id, employee_id, order_number, order_type, state, total_amount, tax_amount, discount_amount, tip_amount, created_time, modified_time, pay_type, item_count, unique_category_count, total_quantity, synced_at FROM orders
WHERE id = $1 LIMIT 1
`

// ==========================================
// Orders
// ==========================================
func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverOrderID,
		&i.EmployeeID,
		&i.OrderNumber,
		&i.OrderType,
		&i.State,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.TipAmount,
		&i.CreatedTime,
		&i.ModifiedTime,
		&i.PayType,
		&i.ItemCount,
		&i.UniqueCategoryCount,
		&i.TotalQuantity,
		&i.SyncedAt,
	)
	return i, err
}

const getOrderCategorySummaryByOrderID = `-- name: GetOrderCategorySummaryByOrderID :many

SELECT id, restaurant_id, order_id, analytic_category_id, item_count, total_quantity, total_amount FROM order_category_summary
WHERE order_id = $1
`

// ==========================================
// Order Category Summary
// ==========================================
func (q *Queries) GetOrderCategorySummaryByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderCategorySummary, error) {
	rows, err := q.db.QueryContext(ctx, getOrderCategorySummaryByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderCategorySummary
	for rows.Next() {
		var i OrderCategorySummary
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.OrderID,
			&i.AnalyticCategoryID,
			&i.ItemCount,
			&i.TotalQuantity,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many

SELECT id, restaurant_id, order_id, product_id, clover_line_item_id, name, quantity, unit_price, total_price, analytic_category_id, created_at, synced_at FROM order_items
WHERE order_id = $1
`

// ==========================================
// Order Items
// ==========================================
func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.OrderID,
			&i.ProductID,
			&i.CloverLineItemID,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.AnalyticCategoryID,
			&i.CreatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByEmployeeAndDate = `-- name: ListOrdersByEmployeeAndDate :many
SELECT id, restaurant_id, clover_order_id, employee_id, order_number, order_type, state, total_amount, tax_amount, discount_amount, tip_amount, created_time, modified_time, pay_type, item_count, unique_category_count, total_quantity, synced_at FROM orders
WHERE employee_id = $1
  AND created_time >= $2
  AND created_time < $3
ORDER BY created_time DESC
`

type ListOrdersByEmployeeAndDateParams struct {
	EmployeeID    uuid.NullUUID `json:"employee_id"`
	CreatedTime   time.Time     `json:"created_time"`
	CreatedTime_2 time.Time     `json:"created_time_2"`
}

func (q *Queries) ListOrdersByEmployeeAndDate(ctx context.Context, arg ListOrdersByEmployeeAndDateParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByEmployeeAndDate, arg.EmployeeID, arg.CreatedTime, arg.CreatedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CloverOrderID,
			&i.EmployeeID,
			&i.OrderNumber,
			&i.OrderType,
			&i.State,
			&i.TotalAmount,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.TipAmount,
			&i.CreatedTime,
			&i.ModifiedTime,
			&i.PayType,
			&i.ItemCount,
			&i.UniqueCategoryCount,
			&i.TotalQuantity,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByRestaurantAndDate = `-- name: ListOrdersByRestaurantAndDate :many
SELECT id, restaurant_id, clover_order_id, employee_id, order_number, order_type, state, total_amount, tax_amount, discount_amount, tip_amount, created_time, modified_time, pay_type, item_count, unique_category_count, total_quantity, synced_at FROM orders
WHERE restaurant_id = $1
  AND created_time >= $2
  AND created_time < $3
ORDER BY created_time DESC
`

type ListOrdersByRestaurantAndDateParams struct {
	RestaurantID  uuid.UUID `json:"restaurant_id"`
	CreatedTime   time.Time `json:"created_time"`
	CreatedTime_2 time.Time `json:"created_time_2"`
}

func (q *Queries) ListOrdersByRestaurantAndDate(ctx context.Context, arg ListOrdersByRestaurantAndDateParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByRestaurantAndDate, arg.RestaurantID, arg.CreatedTime, arg.CreatedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CloverOrderID,
			&i.EmployeeID,
			&i.OrderNumber,
			&i.OrderType,
			&i.State,
			&i.TotalAmount,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.TipAmount,
			&i.CreatedTime,
			&i.ModifiedTime,
			&i.PayType,
			&i.ItemCount,
			&i.UniqueCategoryCount,
			&i.TotalQuantity,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrder = `-- name: UpsertOrder :one
INSERT INTO orders (
    id, restaurant_id, clover_order_id, employee_id, order_number, order_type, state,
    total_amount, tax_amount, discount_amount, tip_amount,
    created_time, modified_time, pay_type,
    item_count, unique_category_count, total_quantity, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (restaurant_id, clover_order_id)
DO UPDATE SET
    employee_id = EXCLUDED.employee_id,
    order_number = EXCLUDED.order_number,
    order_type = EXCLUDED.order_type,
    state = EXCLUDED.state,
    total_amount = EXCLUDED.total_amount,
    tax_amount = EXCLUDED.tax_amount,
    discount_amount = EXCLUDED.discount_amount,
    tip_amount = EXCLUDED.tip_amount,
    created_time = EXCLUDED.created_time,
    modified_time = EXCLUDED.modified_time,
    pay_type = EXCLUDED.pay_type,
    item_count = EXCLUDED.item_count,
    unique_category_count = EXCLUDED.unique_category_count,
    total_quantity = EXCLUDED.total_quantity,
    synced_at = EXCLUDED.synced_at
RETURNING id, restaurant_id, clover_order_id, employee_id, order_number, order_type, state, total_amount, tax_amount, discount_amount, tip_amount, created_time, modified_time, pay_type, item_count, unique_category_count, total_quantity, synced_at
`

type UpsertOrderParams struct {
	ID                  uuid.UUID      `json:"id"`
	RestaurantID        uuid.UUID      `json:"restaurant_id"`
	CloverOrderID       string         `json:"clover_order_id"`
	EmployeeID          uuid.NullUUID  `json:"employee_id"`
	OrderNumber         sql.NullString `json:"order_number"`
	OrderType           sql.NullString `json:"order_type"`
	State               string         `json:"state"`
	TotalAmount         int64          `json:"total_amount"`
	TaxAmount           int64          `json:"tax_amount"`
	DiscountAmount      int64          `json:"discount_amount"`
	TipAmount           int64          `json:"tip_amount"`
	CreatedTime         time.Time      `json:"created_time"`
	ModifiedTime        time.Time      `json:"modified_time"`
	PayType             sql.NullString `json:"pay_type"`
	ItemCount           int32          `json:"item_count"`
	UniqueCategoryCount int32          `json:"unique_category_count"`
	TotalQuantity       int32          `json:"total_quantity"`
	SyncedAt            time.Time      `json:"synced_at"`
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, upsertOrder,
		arg.ID,
		arg.RestaurantID,
		arg.CloverOrderID,
		arg.EmployeeID,
		arg.OrderNumber,
		arg.OrderType,
		arg.State,
		arg.TotalAmount,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.TipAmount,
		arg.CreatedTime,
		arg.ModifiedTime,
		arg.PayType,
		arg.ItemCount,
		arg.UniqueCategoryCount,
		arg.TotalQuantity,
		arg.SyncedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverOrderID,
		&i.EmployeeID,
		&i.OrderNumber,
		&i.OrderType,
		&i.State,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.TipAmount,
		&i.CreatedTime,
		&i.ModifiedTime,
		&i.PayType,
		&i.ItemCount,
		&i.UniqueCategoryCount,
		&i.TotalQuantity,
		&i.SyncedAt,
	)
	return i, err
}

const upsertOrderCategorySummary = `-- name: UpsertOrderCategorySummary :one
INSERT INTO order_category_summary (
    id, restaurant_id, order_id, analytic_category_id, item_count, total_quantity, total_amount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (restaurant_id, order_id, analytic_category_id)
DO UPDATE SET
    item_count = EXCLUDED.item_count,
    total_quantity = EXCLUDED.total_quantity,
    total_amount = EXCLUDED.total_amount
RETURNING id, restaurant_id, order_id, analytic_category_id, item_count, total_quantity, total_amount
`

type UpsertOrderCategorySummaryParams struct {
	ID                 uuid.UUID `json:"id"`
	RestaurantID       uuid.UUID `json:"restaurant_id"`
	OrderID            uuid.UUID `json:"order_id"`
	AnalyticCategoryID uuid.UUID `json:"analytic_category_id"`
	ItemCount          int32     `json:"item_count"`
	TotalQuantity      int32     `json:"total_quantity"`
	TotalAmount        int64     `json:"total_amount"`
}

func (q *Queries) UpsertOrderCategorySummary(ctx context.Context, arg UpsertOrderCategorySummaryParams) (OrderCategorySummary, error) {
	row := q.db.QueryRowContext(ctx, upsertOrderCategorySummary,
		arg.ID,
		arg.RestaurantID,
		arg.OrderID,
		arg.AnalyticCategoryID,
		arg.ItemCount,
		arg.TotalQuantity,
		arg.TotalAmount,
	)
	var i OrderCategorySummary
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.OrderID,
		&i.AnalyticCategoryID,
		&i.ItemCount,
		&i.TotalQuantity,
		&i.TotalAmount,
	)
	return i, err
}

const upsertOrderItem = `-- name: UpsertOrderItem :one
INSERT INTO order_items (
    id, restaurant_id, order_id, product_id, clover_line_item_id, name,
    quantity, unit_price, total_price, analytic_category_id, created_at, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT DO NOTHING
RETURNING id, restaurant_id, order_id, product_id, clover_line_item_id, name, quantity, unit_price, total_price, analytic_category_id, created_at, synced_at
`

type UpsertOrderItemParams struct {
	ID                 uuid.UUID      `json:"id"`
	RestaurantID       uuid.UUID      `json:"restaurant_id"`
	OrderID            uuid.UUID      `json:"order_id"`
	ProductID          uuid.NullUUID  `json:"product_id"`
	CloverLineItemID   sql.NullString `json:"clover_line_item_id"`
	Name               string         `json:"name"`
	Quantity           int32          `json:"quantity"`
	UnitPrice          int64          `json:"unit_price"`
	TotalPrice         int64          `json:"total_price"`
	AnalyticCategoryID uuid.NullUUID  `json:"analytic_category_id"`
	CreatedAt          time.Time      `json:"created_at"`
	SyncedAt           time.Time      `json:"synced_at"`
}

func (q *Queries) UpsertOrderItem(ctx context.Context, arg UpsertOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, upsertOrderItem,
		arg.ID,
		arg.RestaurantID,
		arg.OrderID,
		arg.ProductID,
		arg.CloverLineItemID,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
		arg.AnalyticCategoryID,
		arg.CreatedAt,
		arg.SyncedAt,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.OrderID,
		&i.ProductID,
		&i.CloverLineItemID,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.AnalyticCategoryID,
		&i.CreatedAt,
		&i.SyncedAt,
	)
	return i, err
}
