// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAnalyticCategory = `-- name: CreateAnalyticCategory :one
INSERT INTO analytic_categories (
    id, restaurant_id, name, slug, display_order, color, is_active,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, restaurant_id, name, slug, display_order, color, is_active, created_at, updated_at
`

type CreateAnalyticCategoryParams struct {
	ID           uuid.UUID      `json:"id"`
	RestaurantID uuid.UUID      `json:"restaurant_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	DisplayOrder int32          `json:"display_order"`
	Color        sql.NullString `json:"color"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreateAnalyticCategory(ctx context.Context, arg CreateAnalyticCategoryParams) (AnalyticCategory, error) {
	row := q.db.QueryRowContext(ctx, createAnalyticCategory,
		arg.ID,
		arg.RestaurantID,
		arg.Name,
		arg.Slug,
		arg.DisplayOrder,
		arg.Color,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AnalyticCategory
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Slug,
		&i.DisplayOrder,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnalyticCategory = `-- name: DeleteAnalyticCategory :exec
DELETE FROM analytic_categories
WHERE id = $1
`

func (q *Queries) DeleteAnalyticCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticCategory, id)
	return err
}

const getAnalyticCategoryByID = `-- name: GetAnalyticCategoryByID :one

SELECT id, restaurant_id, name, slug, display_order, color, is_active, created_at, updated_at FROM analytic_categories
WHERE id = $1 LIMIT 1
`

// ==========================================
// Analytic Categories
// ==========================================
func (q *Queries) GetAnalyticCategoryByID(ctx context.Context, id uuid.UUID) (AnalyticCategory, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticCategoryByID, id)
	var i AnalyticCategory
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Slug,
		&i.DisplayOrder,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnalyticCategoryBySlug = `-- name: GetAnalyticCategoryBySlug :one
SELECT id, restaurant_id, name, slug, display_order, color, is_active, created_at, updated_at FROM analytic_categories
WHERE restaurant_id = $1 AND slug = $2
LIMIT 1
`

type GetAnalyticCategoryBySlugParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Slug         string    `json:"slug"`
}

func (q *Queries) GetAnalyticCategoryBySlug(ctx context.Context, arg GetAnalyticCategoryBySlugParams) (AnalyticCategory, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticCategoryBySlug, arg.RestaurantID, arg.Slug)
	var i AnalyticCategory
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Slug,
		&i.DisplayOrder,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByCloverID = `-- name: GetCategoryByCloverID :one
SELECT id, restaurant_id, clover_category_id, name, sort_order, created_at, updated_at, synced_at FROM categories
WHERE restaurant_id = $1 AND clover_category_id = $2
LIMIT 1
`

type GetCategoryByCloverIDParams struct {
	RestaurantID     uuid.UUID `json:"restaurant_id"`
	CloverCategoryID string    `json:"clover_category_id"`
}

func (q *Queries) GetCategoryByCloverID(ctx context.Context, arg GetCategoryByCloverIDParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByCloverID, arg.RestaurantID, arg.CloverCategoryID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverCategoryID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one

SELECT id, restaurant_id, clover_category_id, name, sort_order, created_at, updated_at, synced_at FROM categories
WHERE id = $1 LIMIT 1
`

// ==========================================
// Categories (native Clover categories)
// ==========================================
func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverCategoryID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getCategoryMappingByCategoryID = `-- name: GetCategoryMappingByCategoryID :one

SELECT id, restaurant_id, category_id, analytic_category_id, mapped_by, mapped_at, created_at, updated_at FROM category_mappings
WHERE restaurant_id = $1 AND category_id = $2
LIMIT 1
`

type GetCategoryMappingByCategoryIDParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	CategoryID   uuid.UUID `json:"category_id"`
}

// ==========================================
// Category Mappings
// ==========================================
func (q *Queries) GetCategoryMappingByCategoryID(ctx context.Context, arg GetCategoryMappingByCategoryIDParams) (CategoryMapping, error) {
	row := q.db.QueryRowContext(ctx, getCategoryMappingByCategoryID, arg.RestaurantID, arg.CategoryID)
	var i CategoryMapping
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CategoryID,
		&i.AnalyticCategoryID,
		&i.MappedBy,
		&i.MappedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByCloverItemID = `-- name: GetProductByCloverItemID :one
SELECT id, restaurant_id, clover_item_id, name, description, price, cost, sku, category_id, is_available, is_deleted, created_at, updated_at, synced_at FROM products
WHERE restaurant_id = $1 AND clover_item_id = $2
LIMIT 1
`

type GetProductByCloverItemIDParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	CloverItemID string    `json:"clover_item_id"`
}

func (q *Queries) GetProductByCloverItemID(ctx context.Context, arg GetProductByCloverItemIDParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByCloverItemID, arg.RestaurantID, arg.CloverItemID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverItemID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.Sku,
		&i.CategoryID,
		&i.IsAvailable,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one

SELECT id, restaurant_id, clover_item_id, name, description, price, cost, sku, category_id, is_available, is_deleted, created_at, updated_at, synced_at FROM products
WHERE id = $1 LIMIT 1
`

// ==========================================
// Products
// ==========================================
func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverItemID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.Sku,
		&i.CategoryID,
		&i.IsAvailable,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const listAnalyticCategoriesByRestaurant = `-- name: ListAnalyticCategoriesByRestaurant :many
SELECT id, restaurant_id, name, slug, display_order, color, is_active, created_at, updated_at FROM analytic_categories
WHERE restaurant_id = $1 AND is_active = true
ORDER BY display_order, name
`

func (q *Queries) ListAnalyticCategoriesByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]AnalyticCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticCategoriesByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticCategory
	for rows.Next() {
		var i AnalyticCategory
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Name,
			&i.Slug,
			&i.DisplayOrder,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByRestaurant = `-- name: ListCategoriesByRestaurant :many
SELECT id, restaurant_id, clover_category_id, name, sort_order, created_at, updated_at, synced_at FROM categories
WHERE restaurant_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListCategoriesByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CloverCategoryID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByRestaurant = `-- name: ListProductsByRestaurant :many
SELECT id, restaurant_id, clover_item_id, name, description, price, cost, sku, category_id, is_available, is_deleted, created_at, updated_at, synced_at FROM products
WHERE restaurant_id = $1 AND is_deleted = false
ORDER BY name
`

func (q *Queries) ListProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CloverItemID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.Sku,
			&i.CategoryID,
			&i.IsAvailable,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET is_deleted = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProduct, id)
	return err
}

const updateAnalyticCategory = `-- name: UpdateAnalyticCategory :exec
UPDATE analytic_categories SET
    name = $2,
    slug = $3,
    display_order = $4,
    color = $5,
    is_active = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateAnalyticCategoryParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	DisplayOrder int32          `json:"display_order"`
	Color        sql.NullString `json:"color"`
	IsActive     bool           `json:"is_active"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateAnalyticCategory(ctx context.Context, arg UpdateAnalyticCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateAnalyticCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.DisplayOrder,
		arg.Color,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}

const upsertCategory = `-- name: UpsertCategory :one
INSERT INTO categories (
    id, restaurant_id, clover_category_id, name, sort_order,
    created_at, updated_at, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (restaurant_id, clover_category_id)
DO UPDATE SET
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    updated_at = EXCLUDED.updated_at,
    synced_at = EXCLUDED.synced_at
RETURNING id, restaurant_id, clover_category_id, name, sort_order, created_at, updated_at, synced_at
`

type UpsertCategoryParams struct {
	ID               uuid.UUID     `json:"id"`
	RestaurantID     uuid.UUID     `json:"restaurant_id"`
	CloverCategoryID string        `json:"clover_category_id"`
	Name             string        `json:"name"`
	SortOrder        sql.NullInt32 `json:"sort_order"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	SyncedAt         time.Time     `json:"synced_at"`
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, upsertCategory,
		arg.ID,
		arg.RestaurantID,
		arg.CloverCategoryID,
		arg.Name,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverCategoryID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}

const upsertCategoryMapping = `-- name: UpsertCategoryMapping :one
INSERT INTO category_mappings (
    id, restaurant_id, category_id, analytic_category_id, mapped_by, mapped_at,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (restaurant_id, category_id)
DO UPDATE SET
    analytic_category_id = EXCLUDED.analytic_category_id,
    mapped_by = EXCLUDED.mapped_by,
    mapped_at = EXCLUDED.mapped_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, restaurant_id, category_id, analytic_category_id, mapped_by, mapped_at, created_at, updated_at
`

type UpsertCategoryMappingParams struct {
	ID                 uuid.UUID      `json:"id"`
	RestaurantID       uuid.UUID      `json:"restaurant_id"`
	CategoryID         uuid.UUID      `json:"category_id"`
	AnalyticCategoryID uuid.UUID      `json:"analytic_category_id"`
	MappedBy           sql.NullString `json:"mapped_by"`
	MappedAt           time.Time      `json:"mapped_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertCategoryMapping(ctx context.Context, arg UpsertCategoryMappingParams) (CategoryMapping, error) {
	row := q.db.QueryRowContext(ctx, upsertCategoryMapping,
		arg.ID,
		arg.RestaurantID,
		arg.CategoryID,
		arg.AnalyticCategoryID,
		arg.MappedBy,
		arg.MappedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CategoryMapping
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CategoryID,
		&i.AnalyticCategoryID,
		&i.MappedBy,
		&i.MappedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
    id, restaurant_id, clover_item_id, name, description, price, cost, sku,
    category_id, is_available, is_deleted,
    created_at, updated_at, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (restaurant_id, clover_item_id)
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    cost = EXCLUDED.cost,
    sku = EXCLUDED.sku,
    category_id = EXCLUDED.category_id,
    is_available = EXCLUDED.is_available,
    is_deleted = EXCLUDED.is_deleted,
    updated_at = EXCLUDED.updated_at,
    synced_at = EXCLUDED.synced_at
RETURNING id, restaurant_id, clover_item_id, name, description, price, cost, sku, category_id, is_available, is_deleted, created_at, updated_at, synced_at
`

type UpsertProductParams struct {
	ID           uuid.UUID      `json:"id"`
	RestaurantID uuid.UUID      `json:"restaurant_id"`
	CloverItemID string         `json:"clover_item_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        int64          `json:"price"`
	Cost         sql.NullInt64  `json:"cost"`
	Sku          sql.NullString `json:"sku"`
	CategoryID   uuid.NullUUID  `json:"category_id"`
	IsAvailable  bool           `json:"is_available"`
	IsDeleted    bool           `json:"is_deleted"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SyncedAt     time.Time      `json:"synced_at"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, upsertProduct,
		arg.ID,
		arg.RestaurantID,
		arg.CloverItemID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Cost,
		arg.Sku,
		arg.CategoryID,
		arg.IsAvailable,
		arg.IsDeleted,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.CloverItemID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.Sku,
		&i.CategoryID,
		&i.IsAvailable,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return i, err
}
